config/routes.rb
TestApp::Application.routes.draw do

  devise_for :users

  resources :posts do
    resources :comments
  end

  root :to => 'posts#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities

    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    elsif user.regular?
      can :read, :all
      can :create, Post
      can :manage, Post do |post|
        post && post.author == user
      end
      can :create, Comment
      can :update, Comment do |comment|
        comment && comment.author == user
      end
      can :destroy, Comment do |comment|
        comment && comment.author == user
      end
    else
      can :read, :all
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'

  attr_accessible :text

  validates :text, :post_id, :user_id, :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author, :class_name => 'User', :foreign_key => 'user_id'
  has_many :comments, :dependent => :destroy

  attr_accessible :header, :text

  validates :header, :text, :user_id, :presence => true
  validates :header, length: { maximum: 50 }
  validates :text, length: { maximum: 500 }

end

app/models/role.rb
class Role < ActiveRecord::Base
  ADMIN = 'Admin'
  USER = 'User'

  has_and_belongs_to_many :users

  attr_accessible :name

  def self.get(name)
    Role.find_by_name(name)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :add_default_roles

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :name

  has_many :posts, :dependent => :destroy
  has_and_belongs_to_many :roles

  def admin?
    roles(true).any? { |r| r.name == Role::ADMIN }
  end

  def regular?
    roles(true).any? { |r| r.name == Role::USER }
  end

  private
  def add_default_roles
    roles << Role.get(Role::USER)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  #noinspection RailsParamDefResolve
  before_filter :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_url, :alert => exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit :email, :password, :password_confirmation
    end

    devise_parameter_sanitizer.for(:sign_in) do |u|
      u.permit :email, :password, :password_confirmation
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  #noinspection RailsParamDefResolve
  #before_filter :authenticate_user!
  load_and_authorize_resource :post
  load_and_authorize_resource :comment, :through => :post

  def create
    #@post = Post.find(params[:post_id])
    @comment = @post.comments.build(params[:comment])
    @comment.author = current_user
    @comment.save
    redirect_to post_path(@post)
  end

  def update
    #@post = Post.find(params[:post_id])
    #@comment = @post.comments.find(params[:id])
    @comment.update_attributes(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    #@post = Post.find(params[:post_id])
    #@comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #before_filter :set_post, :except => [:index, :new, :create]
  #noinspection RailsParamDefResolve
  #before_filter :authenticate_user!, except: [:index, :show]

  load_and_authorize_resource :post

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    if @post.save
      flash[:success] = "Post created."
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update_attributes(post_params)
      flash[:success] = "Post updated"
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    if @post.destroy
      flash[:success] = "Post deleted"
    else
      flash[:error] = "Error deleting post"
    end
    redirect_to root_url
  end

  private
    #def set_post
    #  @post = Post.find(params[:id])
    #end

    def post_params
      params.require(:post).permit(:header, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
.row.comment
  %p{id: "comment-text-#{comment.id}"}
    = comment.text

    = form_for [comment.post, comment], html: { class: 'comment-edit-form', id: "comment-edit-form-#{comment.id}" } do |f|
      = f.text_field :text
      = f.submit 'Update', class: 'btn'

  %ul.comment_actions
    - can_update = can?(:update, comment)
    - can_destroy = can?(:destroy, comment)
    - if can_update
      %li
        = link_to 'Edit comment', '#', {class: 'show-comment-edit', id: "show-comment-edit-#{comment.id}"}
    - if can_update && can_destroy
      &nbsp;|&nbsp;
    - if can_destroy
      %li
        = link_to 'Delete comment', [comment.post, comment],
                     :confirm => 'Are you sure?',
                     :method => :delete

app/views/comments/_form.html.haml
.row.span6.comment_form
  = form_for([@post, @post.comments.build]) do |f|
    = f.label :text, 'Add a comment'
    = f.text_field :text

    = f.submit "Submit", class: "btn btn-primary"

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to "Simple blog", root_path, id: "logo"
      %nav
        %ul.nav.pull-right
          %li= link_to "Home", root_path
          - if user_signed_in?
            %li= link_to "New post", new_post_path
            %li= link_to current_user.email, "#"
            %li= link_to "Sign out", destroy_user_session_path, method: "delete"
          - else
            %li= link_to "Sign in", new_user_session_path
            %li= link_to "Sign up", new_user_registration_path

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  %script{ src: "http://html5shim.googlecode.com/svn/trunk/html5.js" }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Simple blog
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = render "layouts/shim"
  %body
    = render "layouts/header"
    .container
      - flash.each do |key, value|
        = content_tag(:div, value, class: "alert alert-#{key}")

      = yield

      = debug(params) if Rails.env.development?

app/views/posts/edit.html.haml
%h1 Edit post
= render :partial => 'shared/post_form', locals: { model: @post }

app/views/posts/index.html.haml
%h1 Posts
- @posts.each do |post|
  .post
    .post-header
      %h3= post.header
    .post-body= post.text
    %ul.post-actions
      %li= link_to 'Full content', post_path(post)
      - if can? :update, post
        %li= link_to 'Edit', edit_post_path(post)
      - if can? :destroy, post
        %li= link_to 'Delete', post_path(post), :method => :delete, :confirm => 'Are you sure?'

app/views/posts/new.html.haml
%h1 New post
= render :partial => 'shared/post_form', locals: { model: @post }

app/views/posts/show.html.haml
%h1= @post.header
.hero-unit= @post.text

%ul.post-actions
  - if can? :update, @post
    %li= link_to 'Edit post', edit_post_path(@post)

  - if can? :destroy, @post
    %li= link_to 'Delete post', post_path(@post), :method => :delete, :confirm => 'Are you sure?'

%h3 Comments
= render @post.comments

- if !current_user.nil? && can?(:create, Comment)
  = render 'comments/form'

app/views/shared/_error_messages.html.haml
- if model.errors.any?
  #error_explanation
    .alert.alert-error
      The form contains
      = pluralize(model.errors.count, "error")

    %ul
      - model.errors.full_messages.each do |msg|
        %li<
          *
          = msg

app/views/shared/_post_form.html.haml
.row
  .span6.offset3
    = form_for(model) do |f|
      -#= render partial: 'shared/error_messages', locals: { model: model }

      = f.label :header
      = f.text_field :header

      = f.label :text
      = f.text_area :text, size: '40x10'

      = f.submit "Submit", class: "btn btn-large btn-primary"